apiVersion: v1
clusters:
- cluster:
    server: https://43.205.211.129:6443
    insecure-skip-tls-verify: true
  name: k3s-cluster
contexts:
- context:
    cluster: k3s-cluster
    user: k3s-user
  name: k3s-context
current-context: k3s-context
kind: Config
users:
- name: k3s-user
  user:
    token: K107c6d8c9eb2de70ca0c8608aa8649e1a9f9ef7b8e4d2a5c1f6b3e8d7a4c2b1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0