apiVersion: v1
kind: Config
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://43.205.210.144:6443
  name: k3s-cluster
contexts:
- context:
    cluster: k3s-cluster
    namespace: default
    user: admin
  name: default
current-context: default
users:
- name: admin
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJnaGEtYWNjZXNzIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmdoYS1hY2Nlc3M6Z2hhLWRlcGxveWVyIn0.working-token