apiVersion: v1
kind: Secret
metadata:
  name: health-api-secrets
  namespace: ${NAMESPACE}
type: Opaque
data:
  DB_PASSWORD: ${DB_PASSWORD_BASE64}
  API_KEY: ${API_KEY_BASE64}
  JWT_SECRET: ${JWT_SECRET_BASE64}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID_BASE64}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY_BASE64}
  AWS_REGION: ${AWS_REGION_BASE64}
  GITHUB_TOKEN: ${GITHUB_TOKEN_BASE64}