# Database Configuration for Different Networks

# Lower Network - Shared Database Secret
apiVersion: v1
kind: Secret
metadata:
  name: database-config
  namespace: health-app-dev
type: Opaque
stringData:
  DB_HOST: "health-app-shared-db.region.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "healthapi"
  DB_USER: "postgres"
  DB_PASSWORD: "changeme123!"
  DATABASE_URL: "postgresql://postgres:changeme123!@health-app-shared-db.region.rds.amazonaws.com:5432/healthapi"

---
apiVersion: v1
kind: Secret
metadata:
  name: database-config
  namespace: health-app-test
type: Opaque
stringData:
  DB_HOST: "health-app-shared-db.region.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "healthapi"
  DB_USER: "postgres"
  DB_PASSWORD: "changeme123!"
  DATABASE_URL: "postgresql://postgres:changeme123!@health-app-shared-db.region.rds.amazonaws.com:5432/healthapi"

---
# Higher Network - Dedicated Database Secret
apiVersion: v1
kind: Secret
metadata:
  name: database-config
  namespace: health-app-prod
type: Opaque
stringData:
  DB_HOST: "health-app-prod-db.region.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "healthapi"
  DB_USER: "postgres"
  DB_PASSWORD: "changeme123!"
  DATABASE_URL: "postgresql://postgres:changeme123!@health-app-prod-db.region.rds.amazonaws.com:5432/healthapi"

---
# ConfigMap for database connection logic
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-connection-script
  namespace: health-app-dev
data:
  connect.sh: |
    #!/bin/bash
    # Test database connection
    export PGPASSWORD=$DB_PASSWORD
    psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -c "SELECT version();"
    
    # Run migrations if needed
    if [ -f "/app/migrations/init.sql" ]; then
      psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -f /app/migrations/init.sql
    fi