apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-api
  labels:
    app: health-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-api
  template:
    metadata:
      labels:
        app: health-api
    spec:
      serviceAccountName: health-app-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: health-api
        image: ghcr.io/arunprabus/health-api:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: health-api-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: health-api-service
spec:
  selector:
    app: health-api
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer