apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-api
  namespace: default
  labels:
    app: health-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-api
  template:
    metadata:
      labels:
        app: health-api
    spec:
      serviceAccountName: health-api-sa
      containers:
      - name: health-api
        image: ghcr.io/arunprabus/health-api:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: health-api-config
              key: AWS_REGION
        - name: DYNAMODB_PROFILES_TABLE
          valueFrom:
            secretKeyRef:
              name: health-api-config
              key: DYNAMODB_PROFILES_TABLE
        - name: DYNAMODB_UPLOADS_TABLE
          valueFrom:
            secretKeyRef:
              name: health-api-config
              key: DYNAMODB_UPLOADS_TABLE
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: health-api-config
              key: S3_BUCKET
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: health-api-service
  namespace: default
spec:
  selector:
    app: health-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: ClusterIP