apiVersion: v1
kind: ServiceMonitor
metadata:
  name: health-api-monitor
spec:
  selector:
    matchLabels:
      app: health-api
  endpoints:
  - port: http
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: health-api-alerts
spec:
  groups:
  - name: health-api
    rules:
    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: High error rate detected
    - alert: PodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
      for: 5m
      labels:
        severity: warning