apiVersion: v1
kind: ServiceAccount
metadata:
  name: health-app-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: health-app-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: health-app-binding
subjects:
- kind: ServiceAccount
  name: health-app-sa
roleRef:
  kind: Role
  name: health-app-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: NetworkPolicy
metadata:
  name: health-app-netpol
spec:
  podSelector:
    matchLabels:
      app: health-api
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontend
    ports:
    - protocol: TCP
      port: 3000
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 443