apiVersion: v1
kind: Secret
metadata:
  name: app-credentials
  namespace: ${NAMESPACE}
type: Opaque
data:
  db-password: ${DB_PASSWORD_BASE64}
  api-key: ${API_KEY_BASE64}
  jwt-secret: ${JWT_SECRET_BASE64}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: ${NAMESPACE}
type: Opaque
data:
  aws-access-key-id: ${AWS_ACCESS_KEY_ID_BASE64}
  aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY_BASE64}
  aws-region: ${AWS_REGION_BASE64}
---
apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: ${NAMESPACE}
type: Opaque
data:
  github-token: ${GITHUB_TOKEN_BASE64}