apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: health-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-repo/dev2prod-healthapp
    targetRevision: HEAD
    path: kubernetes-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true