apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: health-app-dev

resources:
- ../../base/namespaces.yaml
- ../../components/health-api/deployment.yaml
- ../../components/health-api/service.yaml
- ../../components/health-api/configmap.yaml
- ../../components/health-api/secrets.yaml
- ../../components/health-api/hpa.yaml
- ../../components/networking/network-policies.yaml

patchesStrategicMerge:
- deployment-patch.yaml
- configmap-patch.yaml
- hpa-patch.yaml