apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets-system
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/managed-by: terraform
---
# External Secrets Operator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets-controller
  namespace: external-secrets-system
  labels:
    app: external-secrets-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-secrets-controller
  template:
    metadata:
      labels:
        app: external-secrets-controller
    spec:
      serviceAccountName: external-secrets-controller
      containers:
      - name: controller
        image: ghcr.io/external-secrets/external-secrets:v0.9.11
        args:
        - --metrics-addr=:8080
        - --enable-leader-election
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: AWS_REGION
          value: ap-south-1
---
# ServiceAccount for External Secrets
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-controller
  namespace: external-secrets-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/ExternalSecretsRole
---
# ClusterRole for External Secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-controller
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["external-secrets.io"]
  resources: ["*"]
  verbs: ["*"]
---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secrets-controller
subjects:
- kind: ServiceAccount
  name: external-secrets-controller
  namespace: external-secrets-system
---
# SecretStore for AWS Systems Manager
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-ssm-secret-store
  namespace: health-app-dev
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
# ServiceAccount for health-app namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: health-app-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/ExternalSecretsRole
---
# ExternalSecret for database configuration
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: health-api-ssm-secrets
  namespace: health-app-dev
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: aws-ssm-secret-store
    kind: SecretStore
  target:
    name: health-api-ssm-secrets
    creationPolicy: Owner
  data:
  - secretKey: db-host
    remoteRef:
      key: /health-app/dev/database/host
  - secretKey: db-name
    remoteRef:
      key: /health-app/dev/database/name
  - secretKey: db-user
    remoteRef:
      key: /health-app/dev/database/user