apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: parameter-store
  namespace: default
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: health-app-config
  namespace: default
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: parameter-store
    kind: SecretStore
  target:
    name: health-app-config
    creationPolicy: Owner
  data:
  - secretKey: DATABASE_HOST
    remoteRef:
      key: /dev/health-app/database/host
  - secretKey: DATABASE_PORT
    remoteRef:
      key: /dev/health-app/database/port
  - secretKey: DATABASE_NAME
    remoteRef:
      key: /dev/health-app/database/name
  - secretKey: DATABASE_USERNAME
    remoteRef:
      key: /dev/health-app/database/username
  - secretKey: DATABASE_PASSWORD
    remoteRef:
      key: /dev/health-app/database/password
  - secretKey: JWT_SECRET
    remoteRef:
      key: /dev/health-app/api/jwt_secret
  - secretKey: API_PORT
    remoteRef:
      key: /dev/health-app/api/port