apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-ssm-store
  namespace: health-app-dev
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubeconfig-external
  namespace: health-app-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-store
    kind: SecretStore
  target:
    name: kubeconfig-dev
    creationPolicy: Owner
  data:
  - secretKey: config
    remoteRef:
      key: /health-app/kubeconfig/dev