apiVersion: v1
kind: Service
metadata:
  name: health-api-service
  namespace: health-app-${ENVIRONMENT}
  labels:
    app: health-api
    environment: ${ENVIRONMENT}
spec:
  selector:
    app: health-api
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP