---
# Ansible playbook for K3s kubeconfig management
- name: Setup K3s kubeconfig
  hosts: k3s_master
  become: true
  vars:
    cluster_ip: "{{ hostvars['k3s_master']['ansible_host'] }}"
    github_token: "{{ github_token }}"
    repo_name: "{{ repo_name }}"
    environment: "{{ environment }}"
    kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
    
  tasks:
    - name: Wait for K3s to be ready
      wait_for:
        path: "{{ kubeconfig_path }}"
        timeout: 300
      register: k3s_ready
      
    - name: Get kubeconfig content
      slurp:
        src: "{{ kubeconfig_path }}"
      register: kubeconfig_content
      when: k3s_ready.state == "present"
      
    - name: Fix kubeconfig server address
      set_fact:
        fixed_kubeconfig: "{{ kubeconfig_content['content'] | b64decode | replace('127.0.0.1', cluster_ip) | b64encode }}"
      when: kubeconfig_content is defined
      
    - name: Create GitHub secret for kubeconfig
      uri:
        url: "https://api.github.com/repos/{{ repo_name }}/actions/secrets/KUBECONFIG_{{ environment | upper }}"
        method: PUT
        headers:
          Authorization: "token {{ github_token }}"
          Accept: "application/vnd.github.v3+json"
        body_format: json
        body:
          encrypted_value: "{{ fixed_kubeconfig }}"
          key_id: "{{ lookup('env', 'GITHUB_KEY_ID') }}"
        status_code: 201, 204
      when: fixed_kubeconfig is defined
      no_log: true
      
    - name: Verify K3s cluster status
      shell: kubectl get nodes
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: k3s_status
      changed_when: false
      
    - name: Show K3s cluster status
      debug:
        var: k3s_status.stdout_lines