apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- ../../base/namespaces.yaml
- ../../components/monitoring/prometheus.yaml
- ../../components/monitoring/grafana.yaml
- ../../components/networking/network-policies.yaml