---
- name: Install K3s on cluster nodes
  hosts: k3s_nodes
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
    
    - name: Check if K3s is already installed
      systemd:
        name: k3s
      register: k3s_service
      ignore_errors: yes
    
    - name: Get instance metadata
      uri:
        url: "http://169.254.169.254/latest/meta-data/{{ item }}"
        method: GET
        return_content: yes
      register: metadata
      loop:
        - public-ipv4
        - local-ipv4
      when: k3s_service.status.ActiveState != "active"
    
    - name: Set IP variables
      set_fact:
        public_ip: "{{ metadata.results[0].content }}"
        private_ip: "{{ metadata.results[1].content }}"
      when: k3s_service.status.ActiveState != "active"
    
    - name: Install K3s
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --node-ip={{ private_ip }} --advertise-address={{ private_ip }} --tls-san {{ public_ip }} --write-kubeconfig-mode=644 --disable=traefik" sh -
      when: k3s_service.status.ActiveState != "active"
    
    - name: Wait for K3s to be ready
      wait_for:
        port: 6443
        host: "{{ private_ip }}"
        timeout: 300
      when: k3s_service.status.ActiveState != "active"
    
    - name: Verify K3s installation
      command: kubectl get nodes
      register: nodes_output
      retries: 10
      delay: 10
      until: nodes_output.rc == 0
    
    - name: Display cluster status
      debug:
        msg: "{{ nodes_output.stdout_lines }}"