name: Infrastructure Monitoring

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Run Infrastructure Monitoring
      run: |
        chmod +x scripts/rds-monitor.sh
        ./scripts/rds-monitor.sh

    - name: Upload Monitoring Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: monitoring-logs-${{ github.run_number }}
        path: "*.log"
        retention-days: 30