name: SSH to EC2

on:
  workflow_dispatch:
    inputs:
      host:
        description: 'EC2 IP Address'
        required: false
        default: '13.235.42.62'
        type: string
      commands:
        description: 'Commands to run'
        required: false
        default: 'basic'
        type: choice
        options:
          - basic
          - docker
          - system-info
      runner_type:
        description: 'Runner Type'
        required: false
        default: 'aws'
        type: choice
        options:
        - aws
        - github

jobs:
  ssh-ec2:
    runs-on: ${{ github.event.inputs.runner_type == 'aws' && '[self-hosted, awsgithubrunner]' || 'ubuntu-latest' }}
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "❌ SSH_PRIVATE_KEY secret not found"
            exit 1
          fi
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "✅ SSH key configured"
          
          HOST="${{ github.event.inputs.host }}"
          echo "🔍 Testing connection to $HOST..."
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts 2>/dev/null || {
            echo "❌ Cannot reach $HOST on port 22"
            exit 1
          }
          echo "✅ SSH connection ready"

      - name: Run Commands
        run: |
          HOST="${{ github.event.inputs.host }}"
          COMMANDS="${{ github.event.inputs.commands }}"
          
          case $COMMANDS in
            "basic")
              ssh -i ~/.ssh/id_rsa ubuntu@$HOST '
                echo "✅ Connected to $(hostname)"
                whoami && uptime
              '
              ;;
            "docker")
              ssh -i ~/.ssh/id_rsa ubuntu@$HOST '
                echo "🐳 Installing Docker..."
                sudo apt update -qq
                sudo apt install -y docker.io
                docker --version
                sudo systemctl status docker
              '
              ;;
            "system-info")
              ssh -i ~/.ssh/id_rsa ubuntu@$HOST '
                echo "📊 System Information"
                uname -a
                df -h
                free -h
                ps aux --sort=-%cpu | head -10
              '
              ;;
          esac