name: Terraform EC2

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
          - ssh

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        working-directory: simple-ec2
        run: terraform init

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        working-directory: simple-ec2
        run: |
          terraform plan -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
          terraform apply -auto-approve -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
          INSTANCE_IP=$(terraform output -raw instance_ip)
          echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV
          echo "Instance IP: $INSTANCE_IP"

      - name: Verify Instance
        if: github.event.inputs.action == 'apply'
        working-directory: simple-ec2
        run: |
          echo "✅ Instance created successfully"
          echo "Instance IP: $(terraform output -raw instance_ip)"
          echo "SSH Command: ssh -i ~/.ssh/your-key ubuntu@$(terraform output -raw instance_ip)"
          
      - name: SSH Info
        if: github.event.inputs.action == 'ssh'
        run: |
          echo "⚠️ SSH from GitHub Actions is not reliable"
          echo "Use AWS Console or local terminal to SSH"

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        working-directory: simple-ec2
        run: terraform destroy -auto-approve -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"